<?php
declare(strict_types=1);

/**
 * Export utilities for CSV and PDF generation
 */

/**
 * Generate CSV from array data
 */
function generate_csv(array $headers, array $rows): string
{
    $output = fopen('php://temp', 'r+');
    
    // Write headers
    fputcsv($output, $headers);
    
    // Write rows
    foreach ($rows as $row) {
        fputcsv($output, $row);
    }
    
    rewind($output);
    $csv = stream_get_contents($output);
    fclose($output);
    
    return $csv;
}

/**
 * Send CSV file as download
 */
function download_csv(string $filename, array $headers, array $rows): void
{
    $csv = generate_csv($headers, $rows);
    
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Content-Length: ' . strlen($csv));
    header('Cache-Control: no-cache, no-store, must-revalidate');
    header('Pragma: no-cache');
    header('Expires: 0');
    
    echo $csv;
}

/**
 * Generate simple HTML-based PDF (can be enhanced with a PDF library)
 */
function generate_pdf_html(string $title, string $content): string
{
    return "<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>{$title}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        h1 { color: #1d66ff; border-bottom: 2px solid #1d66ff; padding-bottom: 10px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        th { background-color: #f3f4f6; font-weight: bold; }
        tr:nth-child(even) { background-color: #f9fafb; }
        .footer { margin-top: 40px; text-align: center; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <h1>{$title}</h1>
    {$content}
    <div class='footer'>Generated by A+SIS - " . date('Y-m-d H:i:s') . "</div>
</body>
</html>";
}

/**
 * Sanitize filename for safe download
 */
function sanitize_filename(string $filename): string
{
    // Remove any path components
    $filename = basename($filename);
    
    // Remove any non-alphanumeric characters except dots, dashes, and underscores
    $filename = preg_replace('/[^a-zA-Z0-9._-]/', '_', $filename);
    
    // Ensure it has an extension
    if (strpos($filename, '.') === false) {
        $filename .= '.csv';
    }
    
    return $filename;
}

/**
 * Format date for display
 */
function format_date(?string $date, string $format = 'Y-m-d H:i:s'): string
{
    if (!$date) {
        return 'N/A';
    }
    
    try {
        $dt = new DateTime($date);
        return $dt->format($format);
    } catch (Exception $e) {
        return $date;
    }
}

/**
 * Validate email address
 */
function validate_email(string $email): bool
{
    return filter_var($email, FILTER_VALIDATE_EMAIL) !== false;
}

/**
 * Sanitize HTML output
 */
function safe_html(string $text): string
{
    return htmlspecialchars($text, ENT_QUOTES, 'UTF-8');
}

/**
 * Generate pagination HTML
 */
function generate_pagination(int $currentPage, int $totalPages, string $baseUrl): string
{
    if ($totalPages <= 1) {
        return '';
    }
    
    $html = '<div class="pagination" role="navigation" aria-label="Pagination">';
    
    // Previous button
    if ($currentPage > 1) {
        $prevPage = $currentPage - 1;
        $html .= "<a href='{$baseUrl}?page={$prevPage}' aria-label='Previous page'>&laquo; Previous</a>";
    }
    
    // Page numbers
    $startPage = max(1, $currentPage - 2);
    $endPage = min($totalPages, $currentPage + 2);
    
    for ($i = $startPage; $i <= $endPage; $i++) {
        $active = $i === $currentPage ? 'active' : '';
        $ariaCurrent = $i === $currentPage ? 'aria-current="page"' : '';
        $html .= "<a href='{$baseUrl}?page={$i}' class='{$active}' {$ariaCurrent}>{$i}</a>";
    }
    
    // Next button
    if ($currentPage < $totalPages) {
        $nextPage = $currentPage + 1;
        $html .= "<a href='{$baseUrl}?page={$nextPage}' aria-label='Next page'>Next &raquo;</a>";
    }
    
    $html .= '</div>';
    
    return $html;
}
